### ISSUE TITLE
Add Micronaut (bmuschko gradle-docker-plugin) example

### ISSUE THREAD

**Issue by o-shevchenko** [windmilleng/tilt-example-java#31]
[bmuschko](https://github.com/bmuschko/gradle-docker-plugin) is a popular plugin that can build and push a Docker image for your Java application.

We faced a lot of problems during integration, such a plugin with Tilt and deploying it to using Helm on K3d K8s cluster. We use Micronaut framework that [utilizes](https://micronaut-projects.github.io/micronaut-gradle-plugin/snapshot/#_building_docker_images) bmuschko plugin by default.
Could you add an example with the recommended way to do it?
Thanks!
We soled it by using skips_local_docker
```
custom_build(
    'k3d-registry.localhost:5000/myservice',
    './gradlew dockerPushImage',
    deps=['api/src'],
    disable_push=True,
    skips_local_docker=True
)
...
k8s_yaml(helm(
    'bin/k8s/helm/charts/myservice',
    namespace='mynamespace',
    values=['bin/k8s/helm/charts/myservice/values-dev.yaml'])
)
```

**Comment by nicks** [comment]
have you seen this guide?
https://docs.tilt.dev/custom_build.html#custom-docker-builds

you probably want something like 
```
custom_build('myservice', './gradlew dockerBuild && docker tag $GRADLE_OUTPUT_IMAGE $EXPECTED_REF')
```

`skips_local_docker` is intended for more exotic image builders that don't interact with Docker at all. `bmuschko` does interact with docker, so it's not really appropriate for this use-case.

as an aside, we usually strongly discourage hard-coding the local registry name in your tiltfile (we've talked about making it an error when people do this, because it usually means they're confused)

**Comment by o-shevchenko** [comment]
Thanks for your reply.
Yes, I've seen this doc, and I read and tried everything from the doc. Nothing works with such a plugin. I opened two issues.
Only `skips_local_docker` helped to workaround those problems. But I was confused as well about why we should use it and how it helps. So, I created this ticket to get more details about the recommended way of implementing such an integration. 
I provided all the commands I used, and you can reproduce all the issues.

**Comment by o-shevchenko** [comment]
>we usually strongly discourage hard-coding the local registry name in your tiltfile

That's another problem. I get error during k8s_helm deploy if I don't hardcode registry

**Comment by nicks** [comment]
i posted an example here - https://github.com/tilt-dev/tilt-example-java/tree/master/103-micronaut
